mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

mysite/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('permission.urls')),
]

permission/urls.py
from django.conf.urls import url
from permission import views
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls import include
from rest_framework.routers import DefaultRouter
from .views import PerizinanViewSet,CategoryViewSet

router = DefaultRouter()
router.register('perizinan',PerizinanViewSet)
router.register('category',CategoryViewSet)
schema_view = get_swagger_view(title='Perizinan',url='/')
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    # url(r'^perizinan/$', views.PerizinanList.as_view()),
    # url(r'^perizinan/(?P<pk>[0-9]+)/$', views.PerizinanDetail.as_view()),
    url(r'^docs/$', schema_view),
]

permission/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Category(models.Model):
    name = models.CharField(max_length=100)
    note = models.TextField()

    def __str__(self):
        return self.name


class Employee(models.Model):
    number = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.number)


class Perizinan(models.Model):
    employee = models.ForeignKey(User,related_name='perizinan',on_delete=models.CASCADE)
    start = models.DateTimeField(default=timezone.now)
    end = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category,default='none',related_name='perizinan',on_delete=models.CASCADE)
    reason = models.TextField()

    def __str__(self):
        return str(self.employee)

permission/views.py
from rest_framework import status
from rest_framework.response import Response
from permission.models import Category,Perizinan
from django.contrib.auth.models import User
from permission.serializer import PerizinanSerializer,CustomSerializer,CategorySerializer
from rest_framework import permissions
from rest_framework.decorators import api_view, permission_classes
from rest_framework import generics, viewsets
from rest_framework import mixins

class PerizinanViewSet(mixins.CreateModelMixin,
                       mixins.ListModelMixin,
                       mixins.UpdateModelMixin,
                       mixins.RetrieveModelMixin,
                       mixins.DestroyModelMixin,
                       viewsets.GenericViewSet):
       permission_classes = (permissions.IsAuthenticated,)
       serializer_class=PerizinanSerializer
       queryset = Perizinan.objects.all()

class CategoryViewSet(mixins.CreateModelMixin,
                       mixins.ListModelMixin,
                       mixins.UpdateModelMixin,
                       mixins.RetrieveModelMixin,
                       mixins.DestroyModelMixin,
                       viewsets.GenericViewSet):
       permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
       serializer_class=CategorySerializer
       queryset = Category.objects.all()

# class PerizinanList(generics.ListCreateAPIView):
#
#     permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
#     serializer_class = PerizinanSerializer
#
#     def list(self, request):
#         # Note the use of `get_queryset()` instead of `self.queryset`
#         queryset = Perizinan.objects.filter(pk=24)
#         serializer = PerizinanSerializer(queryset, many=True)
#         return Response(serializer.data)
#
# class PerizinanDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Perizinan.objects.all()
#     permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
#     serializer_class = PerizinanSerializer

# @api_view(['GET', 'POST'])
# @permission_classes((permissions.AllowAny,))
# def perizinan_list(request):
#     """
#     List all code perizinan
#     """
#     if request.method == 'GET':
#         # user = User.objects.get(pk=1)
#         serializer = CustomSerializer(data={'perizinan':{'id':1,'user':{'firstname':'tes','lastname':'tes','email':'tess@email.com '},'start':'2018-07-21T11:11:30+07:00','end':'2018-07-21T11:11:30+07:00','category':{'id':1,'name':'tes','note':'sss'},'reason':'sss'}})
#         serializer.is_valid()
#         print(serializer.data)
#         return Response(serializer.data)
#     #Create code perizinan
#     elif request.method == 'POST':
#
#         serializer = PerizinanSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
#
# @api_view(['GET', 'PUT', 'DELETE'])
# @permission_classes((permissions.AllowAny,))
# def perizinan_detail(request, pk):
#     """
#     Retrieve, update or delete a code perizinan.
#     """
#     try:
#         perizinan = Perizinan.objects.get(pk=pk)
#     except Perizinan.DoesNotExist:
#         return Response(status=status.HTTP_404_NOT_FOUND)
#
#     if request.method == 'GET':
#         serializer = PerizinanSerializer(perizinan)
#         return Response(serializer.data)
#
#     elif request.method == 'PUT':
#
#         serializer = PerizinanSerializer(perizinan, data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#
#     elif request.method == 'DELETE':
#         perizinan.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)

permission/templates/permission/category_list.html
{% extends 'permission/index.html' %}
{% block content %}
    {% if user.is_authenticated and perms.permission.add_category %}
      <a class="btn btn-primary" href="/input_category/">Input Category</a><br><br>
    {% endif %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Note</th>
      </tr>
      {%for x in object_list %}
        <tr>
          <td>{{x.name}}</td>
          <td>{{x.note}}</td>
        </tr>
      {%endfor%}
    </table>
{% endblock %}

permission/templates/permission/detail_employee.html
{% extends 'permission/index.html' %}
{% block content %}
  <p>Employee : {{object.employee}}</p>
  <p>Start : {{object.start}}</p>
  <p>End : {{object.end}}</p>
  <p>Category : {{object.category}}</p>
  <p>Reason : {{object.reason}}</p>

  <h4>User Status</h4>
  <p>Username : {{usernamez}}</p>
  <p>Email : {{email}}</p>

{% endblock %}

permission/templates/permission/index.html
{% load static %}
<html>
<head>
   <title>Permission</title>
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
   <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
   <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Pencatatan Izin</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/category/">Category</a>
          <li><a href="/permission/">Permission</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><p style="text-align:right;">Hello,{{ user.get_username }} <a href="/logouts/">Log out</a></p></li>
          {% else %}
            <li><p style="text-align:right;"><a href="/logins/">Login</a></p></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  {% block content %}
    
  {% endblock %}
  </div>

</body>
</html>

permission/templates/permission/input_category.html
{% extends 'permission/index.html' %}
{% block content %}
    <h2>Category Create</h2>
    <ul>
      <form  method="post" id="category_form" >
        {% csrf_token %}
        <!-- <table>
          <tr>
            <td style="width:70px; height:40px;"><label for="your_name">Name</label></td>
            <td><input id="category_name" type="text" name="category_name" required></td>
          </tr>
          <tr>
            <td><label for="your_name">Note </label></td>
            <td><textarea id="category_note" name="category_note" form="category_form" style="resize:none; height:70px;"></textarea></td>
          </tr>
        </table>
        <br/> -->
        {{form.as_p }}
        <input type="submit"class="btn" value="Save">
      </form>

    </ul>
{% endblock %}

permission/templates/permission/input_permission.html
{% extends 'permission/index.html' %}
{% block content %}
  <style>
  body {font-family: Arial, Helvetica, sans-serif;}

  /* The Modal (background) */
  .modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 100px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }

  /* Modal Content */
  .modal-content {
      background-color: #fefefe;
      margin: auto;
      padding: 20px;
      border: 1px solid #888;
      width: 80%;
  }

  /* The Close Button */
  .close {
      color: #aaaaaa;
      float: right;
      font-size: 28px;
      font-weight: bold;
  }

  .close:hover,
  .close:focus {
      color: #000;
      text-decoration: none;
      cursor: pointer;
  }
  #employee_number:hover{
    background-color: red;
  }
  </style>
    <h2>Permission Input</h2>
    <ul>
      <form  method="post" id="permission_form">
        {% csrf_token %}
        <!-- <label for="employee" class="col-sm-1">Employee </label>
        <input type="text" id="employee" name="employee" onclick="myFunction()" readonly required>
        <br>
        <br>
        <label for="start" class="col-sm-1">Start </label>
        <input id="start_date" type="datetime-local" name="start_date" required><br><br>
        <label for="end" class="col-sm-1">End </label>
        <input id="end_date" type="datetime-local" name="end_date" required><br><br>
        <label for="category" class="col-sm-1">Category </label>
        <select id="category" name="category" >
          {%for x in category%}
          <option>{{x.name}}</option>
          {%endfor%}
        </select><br><br>
        <label for="reason" class="col-sm-1">Reason </label>
        <textarea id="reason" name="reason" form="permission_form" style="resize:none; height:50px;"></textarea><br>
        <br> -->
        {{form.as_p}}
        <input class="btn col-sm-1" id="submit" type="submit" value="OK">
      </form>
    </ul>
  </div>
  <div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <h3>Employee List</h3>
      <table class="table" >
        <tr>
          <th>Number</th>
          <th>Name</th>

        </tr>
        {%for x in employee%}
        <tr>
          <td id="employee_number"  onclick="clicked({{x.number}})">{{x.number}}</td>
          <td>{{x.user}}</td>
        </tr>
        {%endfor%}
      </table>

    </div>

  <script>
    var modal = document.getElementById('myModal');
    var span = document.getElementsByClassName("close")[0];
    function myFunction(number) {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    function clicked(number) {
      document.getElementById('employee').value = number;
      modal.style.display = "none";
    }
  </script>
{% endblock %}

permission/templates/permission/login.html
{% extends 'permission/index.html' %}
{% block content %}
      <form method="POST" >
        {% csrf_token %}
      <!-- <label>Username</label>
      <input type="text" name="username" id="username" required>
      <label>Password</label>
      <input type="password" name="password" id="password" required>
      <input class="btn btn-primary" type="submit" value="submit"> -->
      {{form}}
      <input class="btn btn-primary" type="submit" value="submit">
    </form>
{% endblock %}

permission/templates/permission/permission_list.html
{% extends 'permission/index.html' %}
{% block content %}
    {% if user.is_authenticated and perms.permission.add_perizinan %}
    <a class="btn btn-primary" href="/input_permission/">Input Permission</a><br><br>
    {% endif %}
    <table class="table" >
      <tr>
        <th>Employee</th>
        <th>Start</th>
        <th>End</th>
        <th>Category</th>
        {% if user.is_superuser %}<th></th>{% endif %}
      </tr>
      {% if object_list|length == 0  %}
      <tr>
        <td  colspan="5" class="text-center">Data Masih Kosong</td>
      </tr>
      {% else %}
      {%for x in object_list %}
      <tr>
        <td><a href="{% url 'detail_permission' x.id %}">{{x.employee}}</a></td>
        <td>{{x.start}}</td>
        <td>{{x.end}}</td>
        <td>{{x.category}}</td>
        {% if user.is_superuser %}
        <td>
          <a href="/update_permission/{{x.id}}" class="btn btn-default" style="float:left;">Update</a>
          <form method="post" action="/delete_permission/{{x.id}}" style="float:left; margin-left:10%;">{%csrf_token%}
            <input type="hidden" name="perizinan_id" value="{{x.id}}">
            <button type="submit" class="btn btn-default" >X</button>
          </form>
        </td>
        {% endif %}
      </tr>
      {%endfor%}
      {% endif %}
    </table>
{% endblock %}

permission/templates/permission/update_permission.html
{% extends 'permission/index.html' %}
{% block content %}
  <style>
  body {font-family: Arial, Helvetica, sans-serif;}

  /* The Modal (background) */
  .modal {
      display: none; /* Hidden by default */
      position: fixed; /* Stay in place */
      z-index: 1; /* Sit on top */
      padding-top: 100px; /* Location of the box */
      left: 0;
      top: 0;
      width: 100%; /* Full width */
      height: 100%; /* Full height */
      overflow: auto; /* Enable scroll if needed */
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }

  /* Modal Content */
  .modal-content {
      background-color: #fefefe;
      margin: auto;
      padding: 20px;
      border: 1px solid #888;
      width: 80%;
  }

  /* The Close Button */
  .close {
      color: #aaaaaa;
      float: right;
      font-size: 28px;
      font-weight: bold;
  }

  .close:hover,
  .close:focus {
      color: #000;
      text-decoration: none;
      cursor: pointer;
  }
  #employee_number:hover{
    background-color: red;
  }
  </style>
    <h2>Permission Input</h2>
    <ul>
      <form  method="post" id="update_form">
        {% csrf_token %}
        <!-- <label for="employee" class="col-sm-1">Employee </label>
        <input type="text" id="employee" name="employee" onclick="myFunction()" readonly required>
        <br>
        <br>
        <label for="start" class="col-sm-1">Start </label>
        <input id="start_date" type="datetime-local" name="start_date" required><br><br>
        <label for="end" class="col-sm-1">End </label>
        <input id="end_date" type="datetime-local" name="end_date" required><br><br>
        <label for="category" class="col-sm-1">Category </label>
        <select id="category" name="category" >
          {%for x in category%}
          <option>{{x.name}}</option>
          {%endfor%}
        </select><br><br>
        <label for="reason" class="col-sm-1">Reason </label>
        <textarea id="reason" name="reason" form="permission_form" style="resize:none; height:50px;"></textarea><br>
        <br> -->
        {{form.as_p}}
        <input class="btn col-sm-1" id="submit" type="submit" value="OK">
      </form>
    </ul>
  </div>
  <div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <h3>Employee List</h3>
      <table class="table" >
        <tr>
          <th>Number</th>
          <th>Name</th>

        </tr>
        {%for x in employee%}
        <tr>
          <td id="employee_number"  onclick="clicked({{x.number}})">{{x.number}}</td>
          <td>{{x.user}}</td>
        </tr>
        {%endfor%}
      </table>

    </div>

  <script>
    var modal = document.getElementById('myModal');
    var span = document.getElementsByClassName("close")[0];
    function myFunction(number) {
      modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    function clicked(number) {
      document.getElementById('employee').value = number;
      modal.style.display = "none";
    }
  </script>
{% endblock %}